__author__ = 'pluto'

DEFAULT_PAGE_SIZE = 8

#YN 
YN_YES = 1
YN_NO = 0

#INBOUND RECEIPT STATUS
INBOUND_RECEIPT_STATUS_CANCEL = -1
INBOUND_RECEIPT_STATUS_NONE = 0
INBOUND_RECEIPT_STATUS_UNCOMPLETED = 1
INBOUND_RECEIPT_STATUS_COMPLETED = 2

#INBOUND RECEIPT DETAIL STATUS
INBOUND_RECEIPT_DETAIL_STATUS_CANCEL = -1
INBOUND_RECEIPT_DETAIL_STATUS_NONE = 0
INBOUND_RECEIPT_DETAIL_STATUS_PRE_STORAGE = 1
INBOUND_RECEIPT_DETAIL_STATUS_COMPLETED = 2

#BILL TYPE
STORAGE_RECORD_TYPE_RECEIPT = 1